---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istiod
  labels:
    app: istiod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: istiod
  template:
    metadata:
      labels:
        app: istiod
        version: v1
    spec:
      containers:
        - name: istiod
          # From skaffold or values.
          image: {{ .Values.image }}
          #image: pilot-discovery:latest
          imagePullPolicy: Always
          args:
            - "discovery"
            - "--meshConfig"
            - "/var/lib/istio/mesh/mesh.yaml"
            - "--registries"
            - "Mock"
          ports:
            - containerPort: 15010
              name: grpc
            - containerPort: 8080
              name: http
            - containerPort: 15013
              name: tls-grpc
          env:
            - name: REVISION
              value: istiod
            - name: VER
              value: "2"
            - name: GOTRACEBACK
              value: "all"
            # Disable validation webhook
            - name: INJECTION_WEBHOOK_CONFIG_NAME
              value: ""
            - name: VALIDATION_WEBHOOK_CONFIG_NAME
              value: ""
            - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
              value: "true"
            - name: XDS_AUTH
              value: "false"
            - name: POD_NAMESPACE
              value: istiod

          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
          volumeMounts:
            - name: istiod
              mountPath: /var/lib/istio/config
              readOnly: true
            - name: mesh
              mountPath: /var/lib/istio/mesh
              readOnly: true
            - mountPath: /var/run/secrets/istio
              name: istiod-ca-cert
            # Certs will be populated by sidecar !
            - name: istio-envoy
              mountPath: /etc/istio/proxy
            - name: istio-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
            - name: podinfo
              mountPath: /etc/istio/pod

        # Co-located istio Gateway
#        - name: istio-proxy
#          image: costinm/proxyv2:latest
#          args:
#            - "proxy"
#            - "router"
#            #            - "--proxyLogLevel"
#            #            - "trace"
#            - "--serviceCluster"
#            - "istiod"
#          env:
#            - name: XDS_SAVE
#              value: /etc/istio/proxy/
#            - name: XDS_LOCAL
#              value: 0.0.0.0:15015
#            # Save the workload secret to file
#            - name: OUTPUT_CERTS
#              value: /etc/istio/proxy/
#            # Override default ca addr - use real istiod
#            # This will save the certs to a dir, available to local istiod
#            - name: CA_ADDR
#              value: istiod.istio-system.svc:15012
#            - name: PROXY_CONFIG
#              value: |-
#                discoveryAddress: 127.0.0.1:15010
#                zipkin:
#                  address: ""
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  apiVersion: v1
#                  fieldPath: metadata.name
#            - name: POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  apiVersion: v1
#                  fieldPath: metadata.namespace
#
#          ports:
#            # Creates on each host a port forwarder:
#            # -A CNI-DN-78555e74edb8054e88910 -p tcp -m tcp --dport 5000 -j DNAT --to-destination 10.48.0.156:5000
#            - containerPort: 15012
#              name: docker
#              protocol: TCP
#          volumeMounts:
#            - mountPath: /var/run/secrets/istio
#              name: istiod-ca-cert
#            - name: istio-envoy
#              mountPath: /etc/istio/proxy
#            - name: istio-token
#              mountPath: /var/run/secrets/tokens
#              readOnly: true
#            # Not creating those directories disables Secret watching
#            #            - name: ingressgatewaysdsudspath
#            #              mountPath: /var/run/ingress_gateway
#            - name: podinfo
#              mountPath: /etc/istio/pod

      securityContext:
        runAsUser: 0
        runAsGroup: 5228
      volumes:
        - emptyDir:
            medium: Memory
          name: local-certs

        - name: istiod
          configMap:
            name: istiod
            optional: true
        - name: mesh
          configMap:
            name: istiod-mesh
            optional: true

        - name: istiod-ca-cert
          configMap:
            name: istio-ca-root-cert
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: istio-envoy
          emptyDir: {}
        - name: istio-token
          projected:
            sources:
              - serviceAccountToken:
                  path: istio-token
                  expirationSeconds: 43200
                  audience: istio-ca
